from enum import Enum

STRADVISION_XML = "STRADVISION XML"
CVAT_BOX_XML = "CVAT BOX XML"
HUMANF_SEG_JSON = "HUMANF SEG JSON"
PASCAL_VOC_XML = "PASCAL VOC XML"
BO_3D_JSON = "BO_3D JSON"
GPR_JSON = "GPR JSON"
COCO_JSON = "COCO JSON"
ADQ_JSON = "ADQ JSON"
YOLO_V5_TXT = "YOLO_V5 TXT"
LABEL_ON_JSON = "LABEL_ON JSON"

SUPPORTED_LABEL_FILE_EXTENSIONS = ['json', 'xml', 'txt']
# SUPPORTED_LABEL_FORMATS = [STRADVISION_XML, CVAT_BBOX_XML, PASCAL_VOC_XML, GPR_JSON, ADQ_JSON, YOLO_V5_TXT]
SUPPORTED_LABEL_FORMATS = [HUMANF_SEG_JSON, CVAT_BOX_XML, BO_3D_JSON, LABEL_ON_JSON, STRADVISION_XML]
SUPPORTED_IMAGE_FILE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'bmp', 'tiff', 'gif', 'pcd']
SUPPORTED_VIDEO_FILE_EXTENSIONS = "*.mp4 *.avi *.mov"
SUPPORTED_AUDIO_FILE_EXTENSIONS = "*.mp3 *.wav"
